[package]
name = "ffiber"
version = "0.1.0"
authors = ["Gina Yuan <gina.yuan@gmail.com>"]
edition = "2021"

[dependencies]
color-eyre = "0.5"
syn = { version = "1.0.99", features = ["full"] }
which = "4.1.0"

[[example]]
name = "cornflakes"
